version: '3.0'

services:

  #region Commented out example docker compose files
  # quotes:
  #   build:
  #     context: ./QuoteService
  #     dockerfile: app.dockerfile => By default, docker will try to find a file named "Dockerfile" in the context folder. So it's fine to not include this params
  # frontend:
  #   build:
  #     context: ./FrontendApplication
  #     dockerfile: app.dockerfile
  #   ports:
  #     - "8080:80"
  #endregion

  #region Docker compose for specifically implemented services
  frontend:
    build:
      context: ./FrontendApplication
    ports:
      - "8080:8080"
  preprocessing:
    build:
      context: ./Preprocessing
    environment:
      - "PYTHONUNBUFFERED=1"
  #endregion 

  #region Common services
  nginx: # External
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
      # - preprocessing
  api: # Internal
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile 
    environment:
      - "FRONTEND_API=http://frontend:8080"
      - "PREPROCESSING_API=http://preprocessing:5000"
    depends_on:
      - preprocessing
    ports:
      - "3000:3000"
  # webhook:
  #   restart: on-failure
  #   build: ./webhook
  #endregion
